name: Nudge

on:
  workflow_run:
    workflows: [Go Tests, Python Airflow Operator, Release Armada components - RC]
    types: [completed]


jobs:
  nudge:
    runs-on: ubuntu-latest
    environment: nudge
    steps:
      - name: Send notification
        uses: pavlovic-ivan/octo-nudge@v1
        with:
          webhooks: ${{ secrets.NUDGE_WEBHOOKS }}
          conclusions: 'failure,success'